### ISSUE TITLE
User url not breaking and it's not a link

### ISSUE THREAD

**Issue by luizakp** [GeneralMagicio/TE-Academy#247]
**Test Device**
Desktop (2560 × 1600)

**Operating System**
MacOS Monterey

**Browser**
Google Chrome

**Problem Description**
When you login and go to profile the profile url is not wrapped into the card and you can link on the link for it to open on another page

**Steps to Reproduce**
Login and go to profile page

**Visuals**
![image.png](https://images.zenhubusercontent.com/6331f00a3c165167ba355814/a9363de2-7a8b-4363-9b58-fe6524609dee)

**Comment by luizakp** [comment]
PROFILE URL: te-academy.netlify.app/user/undefined

**Comment by VMLVaske** [comment]
Piggybacking on the profile URL: since the extra "public profile" page got removed in a previous design iteration, the URL should ideally be structured in such a way that even as an unregistered, not logged in, external user I can go to the correlating URL and view that students user profile
