### ISSUE TITLE
Profile Cards at "About TE Academy" not identical to figma

### ISSUE THREAD

**Issue by VMLVaske** [GeneralMagicio/TE-Academy#254]
* Link for Twitter / Medium / Linkedin should be in a separate line at bottom of card
* Free Text (below name) should be limited to 2 lines (-> currently for Andrew Penland, there is more text than anticipated,  which also compresses the image above his name)

**Comment by marthendalnunes** [comment]
We've updated that to have 5 lines of description since the te academy team can add personalized links rather than being constrained with the fixed social links (the image distortion link will be fixed in the next production update)
