### ISSUE TITLE
On User Profile, remove Button "View Public Profile"

### ISSUE THREAD

**Issue by VMLVaske** [GeneralMagicio/TE-Academy#261]
Latest design iteration is that the button is not needed anymore

**Comment by markoprljic** [comment]
Why?

**Comment by VMLVaske** [comment]
The Button was meant to direct to the public profile, but after the designs had been greenlighted we made the decision that there will be no additional public profile, instead students can just share their profile URL and other users view the students normal profile. That's why the button became redundant.

**Comment by markoprljic** [comment]
And what happens with the Sidebar nav and FAQ box when viewing someones profile while not being logged in?

**Comment by VMLVaske** [comment]
They disappear if user is not logged in. See the attached Screenshots: 

![Screenshot 2022-09-29 at 14.55.21.png](https://images.zenhubusercontent.com/62a9dd2e14bf035c3dc510d9/839456d2-7e31-4dee-8846-b834a050bdc2
)

![Screenshot 2022-09-29 at 14.56.04.png](https://images.zenhubusercontent.com/62a9dd2e14bf035c3dc510d9/661ec5d2-212b-476a-8224-b6e10e852c7a)
The last one is what people will see that go to the profile URL and are not logged in.

**Comment by markoprljic** [comment]
Ok, thanks.

**Comment by marthendalnunes** [comment]
@VMLVaske actually we'll keep it for simplicity and to save dev time since it's already implemented (it would take us more time to remove the feature than to keep it functional as it is)
