### ISSUE TITLE
"Sign Up" functionality on website

### ISSUE THREAD

**Issue by Vyvy-vi** [GeneralMagicio/TE-Academy#4]
Implement the following Single Sign Ons on the website - 

- "Sign up with Google"
- "Sign up with GitHub"
- "Sign up with Twitter"
- "Sign up with Discord"
- "Sign up with email"

*dependent on wireframes for log in options and login menu from Design teams, but we can start the implementation of the functionality once #1 is completed.

**Comment by marthendalnunes** [comment]
@Vyvy-vi agree that we should use our own login system on the website and use it to create users. But the course itself will be displayed as an iFrame course player on the website (at least that was my take from the calls), so when I mentioned iFrame testing I mean testing Learnworlds single sign-on endpoint + integration with that iFrame course player that is logged in on the LMS with the credentials provided by our website. Does that make sense for you?

**Comment by Vyvy-vi** [comment]
Oh...
I thought we'd redirect to the course website instead of doing iframes

**Comment by VMLVaske** [comment]
Clarification from one of our last calls with Angela: We plan to integrate the learnWorld courses into the TE Academy by iFrames. Further specifics can be discussed with Tobias & Manuel, Angelas Advisors.

**Comment by Vyvy-vi** [comment]
Q) In the call on 29 Jun, Angela mentioned user's getting redirected to the LMS. What direction are we taking?
