### ISSUE TITLE
LMS Integration test

### ISSUE THREAD

**Issue by marthendalnunes** [GeneralMagicio/TE-Academy#6]
Given the initial option of LearnWorlds, we need to test the following integrations to ensure the platform is a viable solution:

- [ ] Check supported LMS authentication methods (does it support OAuth?)
- [ ] Log in integration with the frontend using an iFrame
- [ ] Test course conclusion trigger on [LearnWorlds API](https://learnworlds.dev/docs/api) in order to trigger the NFT Minter
- [ ] Check if the LMS supports custom profile fields (like wallet address)
- [ ] Check if it's possible to fetch user data from the LMS to the website (course completion, number of course participants, etc)

**Comment by marthendalnunes** [comment]
@Vyvy-vi if there's anything else you plan to test on the LMS feel free to add

**Comment by marthendalnunes** [comment]
@Vyvy-vi a few considerations:
- ii. Agree, we can only redirect the student to the LMS when entering a course, with no need to leave the website to register.
- iii. That's exactly the webhook I'm considering using in case we're not using a claim process
- iv. That's an interesting feature, we just have to consider if we're going to solely rely on the LMS as a database for the users' data/wallets. We might also consider having another storage with a link between the student's id provided by the LMS and their wallet address, so if we want to migrate to another solution in the future we can just reassign the user ids in this independent database.
- Actually, there's an endpoint that returns the total students enrolled in a course (https://learnworlds.dev/docs/api/82e3f644375ff-get-analytics-for-a-course). Regarding the chapter/units completed, this endpoint (https://learnworlds.dev/docs/api/458c2a4a0f1a4-get-user-progress-per-course) returns the progress per course, with the `total_units ` of the course, the `completed_units ` of the students, and an array of the progress rate of each unit, so we're covered on that. Also, for the profile page, where we want less granular information about the user progression, we can use this endpoint (https://learnworlds.dev/docs/api/11f74ca895b03-get-user-progress) that returns the same course completion information for every course the student is enrolled.

**Comment by Vyvy-vi** [comment]
Oh that's great! I totally missed those end points

**Comment by VMLVaske** [comment]
Current Status: 
LMS Integration working. User can enroll / un-enroll from course. User get's redirected to LMS Player (did not implement the iFrame in the end). 
Custom Fields (Wallet address), Authentication, fetching user data (i.e. course progress, number of participants) all sufficiently figured out and already implemented or currently being implemented.
