### ISSUE TITLE
There's no link for the Terms of use in the footer

### ISSUE THREAD

**Issue by marthendalnunes** [GeneralMagicio/TE-Academy#88]
We have to check with angela if this should redirect the user to the Terms and conditions page in the website or an external Terms of Use page of the TE Academy newsletter.
Location: footer
![image](https://user-images.githubusercontent.com/18421017/187940968-2eafc96f-0e1c-4f79-bd6b-5c08803c6727.png)

**Comment by VMLVaske** [comment]
![Screenshot 2022-09-23 at 17.23.35.png](https://images.zenhubusercontent.com/62a9dd2e14bf035c3dc510d9/a18f4b8d-e3ec-46f5-bedb-74249aede48c)
Text + Link have been updated. Link points to correct destination (/privacy)
